# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle User Files
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-user-home
    - name: Cache Gradle Files
      uses: actions/cache@v1
      with:
        path: ./.gradle
        key: ${{ runner.os }}-gradle-file
    - name: Cache FG
      uses: actions/cache@v1
      with:
        path: ./arclight-coremod/build
        key: ${{ runner.os }}-fg
    - name: Clean
      run: yes | rm -rf ./arclight-coremod/build/libs
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew idea build --no-daemon -i
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Arclight 
        path: ./arclight-coremod/build/libs/*.*

